system:
  loop_interval_seconds: 90
  log_level: "INFO"
  redis_host: "localhost"
  redis_port: 6379

data_source:
  exchanges: ["coinbase", "kraken"]

harvester_universe:
  symbols: ["BTC_USD_SPOT","ETH_USD_SPOT","SOL_USD_SPOT","AVAX_USD_SPOT","LINK_USD_SPOT","ADA_USD_SPOT","XRP_USD_SPOT","DOGE_USD_SPOT","MATIC_USD_SPOT","DOT_USD_SPOT"]
  timeframe: "1h"
  initial_harvest_days: 1095  # 3 years

screener:
  min_24h_volume_usd: 10000000
  min_price: 0.20
  max_symbols: 15
  snapshot_dir: "data/screener_snapshots"

feeds:
  cryptopanic:
    enabled: false      # flip to true after you add CRYPTO_PANIC_TOKEN in .env
    window_hours: 6
    min_score: -1.0

discovery:
  population_size: 100
  generations_per_cycle: 2
  promotion_criteria:
    min_trades: 75
    min_sortino: 1.25
    max_mdd: 0.20
    min_sharpe: 1.10
    min_win_rate: 0.52

portfolio:
  max_alpha_concentration: 0.50
  kelly_fraction: 0.5
  min_allocation_weight: 0.05

risk:
  daily_stop_pct: 0.10
  equity_floor_pct: 0.50
  max_symbol_weight: 0.35
  max_gross_weight: 1.00

execution:
  primary_exchange: "coinbase"
  mode: "paper"   # paper by default; set "live" later if you choose
  paper_fees_bps: 18
  paper_slippage_bps: 5
